# docker compose up -d {membuat dan menjalankan container}
# docker compose down -v {menghapus container, network, dan volume}

version: "3.8"

services:

  postgresql:
    image: postgres:17
    container_name: taskmanager-postgresql
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=taskmanagerdb
      - POSTGRES_USER=taskmanager
      - POSTGRES_PASSWORD=taskmanager
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    name: taskmanager-postgresql-data